version: "3"
services:
  backend:
    build:
      context: ./app
    ports:
      - "8090:8090"
    volumes:
      - ./app/uploads:/backend/uploads:rw
    restart: always
    networks:
      net-bc:
        ipv4_address: 10.172.17.2

  onnx:
    build:
      context: ./onnx-docker
    ports:
      - "5000:5000"
    volumes:
      - ./app/uploads:/model/uploads:rw
    restart: always
    networks:
      net-bc:
        ipv4_address: 10.172.17.3

networks:
  net-bc:
    ipam:
      config:
        - subnet: 10.172.17.0/24
    
